name: btsnoop_parser
description: Parse HCI snoop logs with this library.
version: 1.0.0
repository: https://github.com/nk521/dart_btsnoop_parser

environment:
  sdk: ^3.2.0

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
